name: Run Test.py

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/15 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r Files/tester/requirements.txt

      - name: Install Xray
        run: |
          wget https://github.com/XTLS/Xray-core/releases/latest/download/xray-linux-64.zip
          unzip xray-linux-64.zip -d /usr/local/bin/
          chmod +x /usr/local/bin/xray

      - name: Check installed packages
        run: |
          pip list

      - name: Execute Python script
        run: |
          python Files/tester/Test.py

      - name: Save Xray logs
        if: always()
        run: |
          cat /tmp/xray.log || echo "No Xray logs found"

      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update tested configs"
