name: V2Ray Config Aggregator

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build-and-collect:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Install dependencies
      run: |
        cd Files
        go mod tidy

    - name: Build and run Go aggregator
      run: |
        cd Files
        go build -o ../aggregator *.go
        cd ..
        ./aggregator

    - name: Verify output files
      run: |
        ls -l
        ls -l Base64/
        ls -l Splitted-By-Country/
        ls -l Splitted-By-Protocol/

    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add -A
        git commit -m "Update V2Ray configs $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
